### ISSUE TITLE
Sync node state when candidateblock message received.

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-signer#141]
State synchronization between the current nodes works as follows.
When a node with Member status receives a candidateblock message, it recognizes that a new round has started as the sender of that message as the master. By doing this, even if there are multiple rounds that treat different nodes as masters, they will converge to one round.
However, when there are two or more Master nodes at the same time, there is a case that two rounds will continue to exist forever. That is #113.

I propose the following changes in order to converge to one round even if there are multiple Master nodes.

## The current behavior

> 1. Start Next Round
>      * Sleep 60 secs. (This is default value. It can be changed by --duration option.)
> 2. Produce a candidate block
>      * Call getnewblock
>      * ...
> 
> from: https://github.com/chaintope/tapyrus-signer#round-master-flow

In the current behavior, Master nodes just sleep while round-duration.

## Proposed behavior

I introduce the round duration timer that is for waiting round-duration time passed. If the node receives candidateblock while waiting time up, the node will work as a Member node of the round that is started by the candidateblock message sender.

 1. Start Next Round
     * If the round-duration timer is not started
          *  The node starts the timer for counting the round-duration
     * If the round-duration timer is started
          * If the timer is not up
               * If the node receives candidateblock message
                    * The node works as a Member node and leaves this flow.
               * The node sleep 500ms
               * The node goes next loop.
          * If the timer is up
               * The node goes 2nd step.
2. Produce a candidate block
     * Call getnewblock
     * ...

**Comment by Yamaguchi** [comment]
A problem is that member nodes can not avoid a malicious signer to be chosen when a malicious signer chooses himself as the master and send candidateblock message to other nodes.
But I think the proposed idea makes signer more stable.

**Comment by rantan** [comment]
Thanks for your comment. It is true. This proposal (and also current behavior) cannot deal to avoid malicious signers.
I think we should consider how to avoid malicious signers as another issue.

**Comment by rantan** [comment]
I created an issue for the malicious signers. #144
