### ISSUE TITLE
Use rust-tapyrus crate

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-signer#28]

**Comment by Yamaguchi** [comment]
We should not use curv library, because 
- it does not fit our use cases or may has some problem.
- We prefer MIT than GPLv3.

**Comment by rantan** [comment]
In this PR, just replace rust-bitcoin to rust-tapyrus

> We should not use curv library, because
> 
> * it does not fit our use cases or may has some problem.
> * We prefer MIT than GPLv3.
In #51, we treat this.
