### ISSUE TITLE
The node should not receive self sending messages.

### ISSUE THREAD

**Issue by rantan** [chaintope/tapyrus-signer#36]
# Motivation

Now, signer nodes receive and process messages which was sent by themselves. Current messages are delivered on Redis pub/sub. So, sender can receive own message same as other signers sent.
However, when the way sending message is changed, current behavior would not be able to keep. Creating tcp connection to myself is not effective. This behavior should be change.

# What it should be.

* Change ConnectionManager behavior to ignore when received messages sent by themselves.
* Change each message processor functions to make them work without receiving messages sent by themselves.

**Comment by Yamaguchi** [comment]
A node uses `ConnectionManager#send_message(message: Message)` when it sends `Blockvss` message.
In this case, the node already avoids sending message to itself.

Node uses `ConnectionManager#broadcast_message(message: Message)`.
Node receives the messages sent from own node when it uses `broadcast_message`.
