### ISSUE TITLE
Sorting rule of public keys. 

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-signer#61]
In current implementation, public keys of signers are sorted internally.
https://github.com/chaintope/tapyrus-signer/blob/master/src/signer_node/node_parameters.rs#L38

Sorting PublicKey is based on concatenating of (x-coordinate || y-coordinate) of the point, where each coordinate is decoded as hex string with little endian.

On the other hand, a public key in Tapyrus is usually encoded as big endian and prefixed '02' or '03'.

it is better to change the rule so that public keys are sorted based on 'compressed public key' because current implementation is not intuitive

**Comment by azuchi** [comment]
Currently, signer config has compressed public key format.
https://github.com/chaintope/tapyrus-signer/blob/master/tests/resources/signer_config_sample.toml#L4-L8

You means adding a check for a compressed public key?

**Comment by Yamaguchi** [comment]
> You means adding a check for a compressed public key?

No.

For example, if we have 3 public keys,

- Alice : 033cfe7fa1be58191b9108883543e921d31dc7726e051ee773e0ea54786ce438f8
- Bob : 020464074b94702e9b07803d247021943bdcc1f8700b92b66defb7fadd76e80acf
- Carol : 02cbe0ad70ffe110d097db648fda20bef14dc72b5c9979c137c451820c176ac23f

The result of sorting signers(Alice, Bob, Carol) based on lexical order is Bob -> Carol -> Alice.
So I expected that the round master would be Bob, Carol, Alice, Bob, ...,  in turn.
But actually the round master will be Carol, Bob, Alice, ...

It is because sorting of tapyrus::util::key::PublicKey depends on sorting of secp256k1::PublicKey which is based on concatenating of (x-coordinate as little-endian || y-coordinate as little-endian ), not lexical order of compressed public key format.

x-coordinate of the point corresponding to the public key.

- Alice: f838e4....
- Bob: cf0ae8...
- Carol: 3fc26a...

To use lexical order to sort public is useful because 
1. we can know the next master node easily.
2. we should specify "index" of signers to computing secret share in setting up.

**Comment by Yamaguchi** [comment]
日本語で書くと、
今のpublickeyのソートが「EC上の点のlittle-endianで表したx座標の順」で、それがマスターの順序やVSSの生成に影響している。

「EC上の点のlittle-endianで表したx座標の順」よりも「圧縮公開鍵」の辞書順にした方がよいのではないかというのが上の主張。

セットアップの際には上記の順序を考慮してVSSを作らなければいけないが、今のところはオフラインでソートする想定なので、辞書順にした方がセットアップ手順がシンプルになるのではないかと考えている。

また、ラウンドのマスターの順番も一目ではわかりにくい。

**Comment by azuchi** [comment]
I see. ACK.

**Comment by rantan** [comment]
From the beginning it should be sorted as dictionary order of compressed public key. 
If not, i think it is bug and it should be fix.
