### ISSUE TITLE
Command tool for trustless set up.

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-signer#64]
Implement a command-line tool for 'trustless' setting up.

see https://github.com/chaintope/tapyrus-signer/pull/56/files#diff-e595d437fa9c89e020d90c05f790e241R1

**Comment by rantan** [comment]
This issue means for un-trusted set up, right?

**Comment by Yamaguchi** [comment]
> This issue means for un-trusted set up, right?

Yes
