### ISSUE TITLE
Add the parameters to configuration file for the federation management

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-signer#66]
We need to add some parameters for federation management.

see https://github.com/chaintope/tapyrus-signer/pull/56/files#diff-67c17f37d35387f65e7ac8b38705f8c1R1

**Comment by rantan** [comment]
# The goal of this issue

Make tapyrus-signer node starts with new federation parameters.
Issue #69 takes on storing settings into disk. So it is not on this issue.

## Mini tasks

* [ ] Add new parameters into node argument.
* [ ] Make the signer node possible to start with new parameters.
* [ ] Remove key generation protocol codes.
