### ISSUE TITLE
RPC API for Signing block(s)

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-signer#7]
For initializing and staring tapyrus core network, we need to sign genesis block.

After Schnorr signature and secret sharing, the initializing process is like this:

1. Run all signer nodes.(without running tapyrus-core)
2. Execute tapyrus-genesis command. This returns block data without signature as a hex string.
3. Post RPC request to one of the signer nodes. (using curl command, for example)
    - The request contains block hex acquired in Step 2
    - Signer nodes communicate with each other and generate an aggregated signature.
    - The signer node which received the request returns this signature.
4. Add the signature to the genesis block. and store in genesis.dat
5. Run tapyrus core.
‌
So, we should implement the RPC server running on signer nodes.
The following is the example of an execution RPC API.

```
$ curl -X POST -H 'Content-Type: application/json'
          -d '{"method":"signblock", "params": [
               "testnet",
               "01000000000000000000000000000000000000000000000000000000000000000000000040c0a1ab811db9d7e58a8c49bf1a5520940dcae7a8446c44eb081bb4a3ae73cc6a6e4759315ab07c4255b40b368ddbe96ff7cb2602b491d88d8d6a7709d7490501d2bb5d0100000020010000000000000000000000000000000000000000000000000000000000000000000000002221025700236c2890233592fcef262f4520d22af9160e3d9705855140eb2aa06c35d3ffffffff0100f2052a010000001976a914834e0737cdb9008db614cd95ec98824e952e3dc588ac00000000"
          ]}' http://signer1:8080
$ {
    "signature": "40b078775e32c8b7e469f1feac8430dec294bc1bb45504ff609cd0b969a46403069bdaca8b4eea707c57894c56007c7cc3503d6a1aad6b8aba568c117e71cc6f62",
    "publickey": "025700236c2890233592fcef262f4520d22af9160e3d9705855140eb2aa06c35d3",
    "block": "01000000000000000000000000000000000000000000000000000000000000000000000040c0a1ab811db9d7e58a8c49bf1a5520940dcae7a8446c44eb081bb4a3ae73cc6a6e4759315ab07c4255b40b368ddbe96ff7cb2602b491d88d8d6a7709d7490501d2bb5d40b078775e32c8b7e469f1feac8430dec294bc1bb45504ff609cd0b969a46403069bdaca8b4eea707c57894c56007c7cc3503d6a1aad6b8aba568c117e71cc6f620100000020010000000000000000000000000000000000000000000000000000000000000000000000002221025700236c2890233592fcef262f4520d22af9160e3d9705855140eb2aa06c35d3ffffffff0100f2052a010000001976a914834e0737cdb9008db614cd95ec98824e952e3dc588ac00000000"
}
```

**Comment by rantan** [comment]
This issue must be implemented for to start new Tapyrus network on distributed signers.

**Comment by rantan** [comment]
We are going to take another way for this issue. It is proposed in PR #56.
