### ISSUE TITLE
Unify  a format of the arguments.

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrus-signer#91]
Arguments of the `tapyrus-signerd` should be updated.
For now, 
- one is snake_case(`to_address`),
- one is kebab-case(`skip-waiting-ibd`)
- others are simply concatenating lower case words.

**Comment by rantan** [comment]
I prefer 3rd one which is "others are simply concatenating lower case words.".
Because tapyrusd uses this one.

However, consistency is most important. I don't mind which one is selected.

**Comment by Yamaguchi** [comment]
Concatenating lower case words is sometimes hard to read, I think.

**Comment by azuchi** [comment]
> Concatenating lower case words is sometimes hard to read, I think.

I think so too. About cli option, I like kebab-case.
